name: Health check

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service urls
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-bxxx.onrender.com/health
