name: Health check

on:
  push:
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service health url
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-bxxx.onrender.com/health
